name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        check-latest: true

    - name: Install dependencies
      run: make deps
      
    - name: Build Plugin
      run: make plugin
      
    - name: Build CLI
      run: make cli
